############# Housekeeping

- alias: Database Purge
  trigger:
    platform: time
    at: '12:00:00'
  action:
    - service: recorder.purge
      data:
        keep_days: 14
#        repack: true




############# Gaeste Zimmer

#- alias: "Gaestezimmer Luftfeuchtigkeit"
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.humidity_158d0002c8cfcb
#    above: 60
#    for:
#       hours: 0
#       minutes: 10
#  action:
#    - service: tts.google_translate_say
#      entity_id: media_player.living_room_speaker
#      data:
#        message: 'Luefsten im Gaestezimmer'  
#        language: 'de'

    


############Basti Lampe
- alias: Wandschalter zu Lampe An
  trigger:
     platform: state
     entity_id: switch.basti_lampe  
     from: 'off'
     to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.basti_lampe_internal
           

- alias: Wandschalter zu Lampe Aus
  trigger:
     platform: state
     entity_id: switch.basti_lampe  
     from: 'on'
     to: 'off'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.basti_lampe_internal      


############Basti Switch
- alias: Single Press - Basti Switch
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001f3793a
      click_type: single
  action:
    - service: switch.toggle
      data:
        entity_id: switch.basti_decke

- alias: Double Press - Basti Switch
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001f3793a
      click_type: double
  action:
    - service: switch.toggle
      data:
        entity_id: switch.basti_lampe

- alias: Long Press - Basti Switch
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001f3793a
      click_type: long_click_press
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.basti_lampe
    - service: switch.turn_off
      data:
        entity_id: switch.basti_decke


############Basti Bed Switch
- alias: Single Press - Basti Bed Switch
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001f3def4
      click_type: single
  action:
    - service: switch.toggle
      data:
        entity_id: switch.basti_decke

- alias: Double Press - Basti Bed Switch
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001f3def4
      click_type: double
  action:
    - service: switch.toggle
      data:
        entity_id: switch.basti_lampe

- alias: Long Press - Basti Bed Switch
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001f3def4
      click_type: long_click_press
  action:
    - service: switch.toggle
      data:
        entity_id: switch.basti_lampe
    - service: switch.toggle
      data:
        entity_id: switch.basti_decke




############Kueche

- alias : Küche an um 06:45
  initial_state: false
  trigger:
    platform: time
    at : '06:30:00'
  condition:
     - condition: time
       weekday:
         - mon
         - tue
         - wed
         - thu
         - fri    
  action:
    service: script.kueche_on


- alias : Küche aus um 07:15
  initial_state: false
  trigger:
    platform: time
    at: '07:15:00'
  action:
    service: script.kueche_off


- alias: Erinnerung Tagesschau
  initial_state: true
  trigger: 
    platform: time
    at: '19:58:00'
  action:
    service: tts.google_translate_say
    entity_id: media_player.living_room_speaker
    data:
      message: 'Tagesschau in 2 Minuten'  
      language: 'de'


#- alias: Turn on kitchen light when there is movement
#  initial_state: false
#  hide_entity: True
#  trigger:
#    platform: state
#    entity_id: binary_sensor.motion_sensor_158d0002239b1a
#    to: 'on'
#  action:
#    service: script.kueche_on


#- alias: Turn off kitchen light 2 minutes after last movement
#  initial_state: false
#  hide_entity: True
#  trigger:
#    platform: state
#    entity_id: binary_sensor.motion_sensor_158d0002239b1a
#    to: 'off'
#    for:
#      minutes: 1
#  action:
#    service: script.kueche_off

      
     
     
- alias: Single Press - Kitchen toggle 
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000223e5a8
      click_type: single
  action:
    - service: script.kueche_toggle
    - service: homeassistant.turn_off
      entity_id: script.kuechen_licht_stop_all_timer_scripts    
    

- alias: Double Press - Wohnzimmer Decke
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000223e5a8
      click_type: double
  action:
    - service: switch.toggle
      entity_id: switch.wohnzimmer_decke

    

- alias: Long press - Licher im Wohnzimmer und Küche aus
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d000223e5a8
      click_type: long_click_press
  action:
    - service: script.kueche_off
    - service: switch.turn_off
      entity_id: switch.couch    
    - service: script.tisch_off    
    - service: light.turn_off
      entity_id: light.gateway_light_7811dcded114
    


################################################################################################
############ KUECHE CUBE 
################################################################################################


- alias: Cube to flip90
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00024a48bd_2
      action_type: flip90
  action:
    - service: switch.toggle
      entity_id: switch.04200102dc4f222a335a

- alias: Cube to tab-twice
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00024a48bd_2
      action_type: tap_twice
  action:
    - service: switch.toggle
      entity_id: switch.couch


- alias: Cube to move
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00024a48bd_2
      action_type: move
  action:
    - service: script.kueche_toggle      

- alias: Cube to shake_air
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00024a48bd_2
      action_type: shake_air
  action:
    service: script.spiele_sr1_marshall

- alias: Cube to free_fall
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00024a48bd_2
      action_type: free_fall
  action:
    - service: media_player.media_stop
      entity_id: media_player.stanmoreblackb269_3



- alias: Cube to flip180
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00024a48bd_2
      action_type: flip180
  action:
    service: script.gute_nacht
    #- service: xiaomi_aqara.play_ringtone
    #  data:
    #    gw_mac: 78:11:DC:DE:D1:14
    #    ringtone_id: 2
    #    ringtone_vol: 1

- alias: Cube to rotate
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.cube_158d00024a48bd_2
      action_type: rotate
  action:
      service_template: >
         {% if trigger.event.data.action_value | float > 20 %}
           script.marshall_volume_up3
         {% elif trigger.event.data.action_value | float > 15 %}
           script.marshall_volume_up3
         {% elif trigger.event.data.action_value | float > 10 %}
           script.marshall_volume_up2
         {% elif trigger.event.data.action_value | float > 0 %}
           script.marshall_volume_up1
         {% elif trigger.event.data.action_value | float < -20 %}
           script.marshall_volume_down3
         {% elif trigger.event.data.action_value | float < -15 %}
           script.marshall_volume_down3
         {% elif trigger.event.data.action_value | float < -10 %}
           script.marshall_volume_down2
         {% elif trigger.event.data.action_value | float < 0 %}
           script.marshall_volume_down1
         {% endif %}


#flip90, flip180, move, tap_twice, shake_air, swing, alert, free_fall and rotate



################################################################################################
############ BASTI CUBE 
################################################################################################

- alias: B-Cube to move
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.bcube
      action_type: move
  action:
    - service: script.music_box_next


- alias: B-Cube to tab twice
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.bcube
      action_type: tap_twice
  action:
    - service: script.music_box_play_pause 
#    - service: script.bastian_arbeitsplatz_an
#    - service: switch.turn_on 
#      entity_id: switch.boxen
#    - service: switch.turn_on
#      entity_id: switch.media_center
      


- alias: B-Cube to air-shake
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.bcube
      action_type: shake_air
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.media_pc

- alias: B-Cube to flip90
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.bcube
      action_type: flip90
  action:
    - service: script.bastian_arbeitsplatz_an
#    - service: switch.turn_on
#      data:
#        entity_id: switch.carbon_x1




- alias: B-Cube to flip180
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.bcube
      action_type: flip180
  action:
    - service: switch.turn_off
      entity_id: switch.boxen
#    - service: switch.turn_off 
#      entity_id: switch.media_center # media_center
#    - service: switch.turn_off
#      entity_id: switch.media_pc
    

- alias: B-Cube to rotate
  trigger:
    platform: event
    event_type: xiaomi_aqara.cube_action
    event_data:
      entity_id: binary_sensor.bcube
      action_type: rotate
  action:
      service_template: >
         {% if trigger.event.data.action_value | float > 20 %}
           script.music_box_volume_up4
         {% elif trigger.event.data.action_value | float > 15 %}
           script.music_box_volume_up3
         {% elif trigger.event.data.action_value | float > 10 %}
           script.music_box_volume_up2
         {% elif trigger.event.data.action_value | float > 0 %}
           script.music_box_volume_up1
         {% elif trigger.event.data.action_value | float < -20 %}
           script.music_box_volume_down4
         {% elif trigger.event.data.action_value | float < -15 %}
           script.music_box_volume_down3
         {% elif trigger.event.data.action_value | float < -10 %}
           script.music_box_volume_down2
         {% elif trigger.event.data.action_value | float < 0 %}
           script.music_box_volume_down1
         {% endif %}


################################################################################################
############ Kammer
################################################################################################

- alias: Kammer-Licht bei Bewegung
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002239b1a
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.kammer

- alias: Lammerlicht Aus nach 2 Minuten 
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002239b1a
    to: 'off'
    for:
      minutes: 2
  action:
    service: homeassistant.turn_off
    entity_id: switch.kammer
    
- alias: Cloud Webhooks 
  trigger:
    platform: event
    event_type: ifttt_webhook_received
    event_data:
      action: call_service
  action:
    service_template: '{{ trigger.event.data.service }}'
    data_template:
      entity_id: '{{ trigger.event.data.entity_id }}'    



################################################################################################
############ RF Remote
################################################################################################

- alias: RF Ok-> Decke Basti
  trigger:
    platform: event
    event_type: keyboard_remote2_command_received
    event_data:
      device_descriptor: "/dev/input/by-id/usb-OSMC_Remote_Controller_USB_Keyboard_Mouse-event-kbd"
      key_code: 28 # ok
  action:
    service: light.toggle
    entity_id: light.bastian_decke

- alias: RF OK long press-> Lampe Basti
  trigger:
    platform: event
    event_type: keyboard_remote2_command_received
    event_data:
      device_descriptor: "/dev/input/by-id/usb-OSMC_Remote_Controller_USB_Keyboard_Mouse-event-kbd"
      key_code: 1028 # ok
  action:
    service: light.toggle
    entity_id: light.bastian_lampe



- alias: RF Info-> Nuprime Display
  trigger:
    platform: event
    event_type: keyboard_remote2_command_received
    event_data:
      device_descriptor: "/dev/input/by-id/usb-OSMC_Remote_Controller_USB_Keyboard_Mouse-event-kbd"
      key_code: 23 # info
  action:
    service: script.office_hub_nuprime_toggle_display
    

- alias: RF Home -> Boxen an/ Media PC an / Rega Mute
  trigger:
    platform: event
    event_type: keyboard_remote2_command_received
    event_data:
      device_descriptor: "/dev/input/by-id/usb-OSMC_Remote_Controller_USB_Keyboard_Mouse-event-kbd"
      key_code: 102 # home
  action:
    - service: switch.turn_on
      entity_id: switch.boxen
    - service: script.media_pc_an
      

- alias: RF Home long press-> Boxen aus 
  trigger:
    platform: event
    event_type: keyboard_remote2_command_received
    event_data:
      device_descriptor: "/dev/input/by-id/usb-OSMC_Remote_Controller_USB_Keyboard_Mouse-event-kbd"
      key_code: 1102 # home
  action:
    - service: script.musik_station_aus
      


- alias: RF Menu-> Nuprime Input next 
  trigger:
    platform: event
    event_type: keyboard_remote2_command_received
    event_data:
      device_descriptor: "/dev/input/by-id/usb-OSMC_Remote_Controller_USB_Keyboard_Mouse-event-kbd"
      key_code: 46 # menu 
  action:
    service: script.office_hub_music_box_input_next

- alias: RF Menu long press-> Nuprime Input prev
  trigger:
    platform: event
    event_type: keyboard_remote2_command_received
    event_data:
      device_descriptor: "/dev/input/by-id/usb-OSMC_Remote_Controller_USB_Keyboard_Mouse-event-kbd"
      key_code: 1046 # menu 
  action:
    service: script.office_hub_music_box_input_prev


- alias: RF Right-> Next song
  trigger:
    platform: event
    event_type: keyboard_remote2_command_received
    event_data:
      device_descriptor: "/dev/input/by-id/usb-OSMC_Remote_Controller_USB_Keyboard_Mouse-event-kbd"
      key_code: 106 # Right
  action:
    service: script.music_box_next_track


- alias: RF Right long press -> Play pause 
  trigger:
    platform: event
    event_type: keyboard_remote2_command_received
    event_data:
      device_descriptor: "/dev/input/by-id/usb-OSMC_Remote_Controller_USB_Keyboard_Mouse-event-kbd"
      key_code: 1106 # Right
  action:
    service: script.music_box_play_pause



- alias: RF Left-> Prev Song
  trigger:
    platform: event
    event_type: keyboard_remote2_command_received
    event_data:
      device_descriptor: "/dev/input/by-id/usb-OSMC_Remote_Controller_USB_Keyboard_Mouse-event-kbd"
      key_code: 105 # left
  action:
    service: script.music_box_prev_track


- alias: RF Up-> Seek +30sec
  trigger:
    platform: event
    event_type: keyboard_remote2_command_received
    event_data:
      device_descriptor: "/dev/input/by-id/usb-OSMC_Remote_Controller_USB_Keyboard_Mouse-event-kbd"
      key_code: 103 # up 
  action:
    service: script.music_box_seek_forward
#    service: media_player.media_seek
#    entity_id: media_player.digione_3
#    data:
#      seek_position: 30

- alias: RF Down-> Seek -10sec
  trigger:
    platform: event
    event_type: keyboard_remote2_command_received
    event_data:
      device_descriptor: "/dev/input/by-id/usb-OSMC_Remote_Controller_USB_Keyboard_Mouse-event-kbd"
      key_code: 108 # down
  action:
    service: media_player.media_seek
    entity_id: media_player.digione_3
    data:
      seek_position: -10



- alias: RF Vol-Down-> Vol down
  trigger:
    platform: event
    event_type: keyboard_remote2_command_received
    event_data:
      device_descriptor: "/dev/input/by-id/usb-OSMC_Remote_Controller_USB_Keyboard_Mouse-event-kbd"
      key_code: 12 # vol down
  action:
    service: script.music_box_volume_down1
    #service: script.office_hub_nuprime_volume_down3
    

- alias: RF Vol-Down long press-> Vol down 10
  trigger:
    platform: event
    event_type: keyboard_remote2_command_received
    event_data:
      device_descriptor: "/dev/input/by-id/usb-OSMC_Remote_Controller_USB_Keyboard_Mouse-event-kbd"
      key_code: 1012 # vol down
  action:
    service: script.music_box_preamp_volume_down1

- alias: RF Vol-Up-> Vol up
  trigger:
    platform: event
    event_type: keyboard_remote2_command_received
    event_data:
      device_descriptor: "/dev/input/by-id/usb-OSMC_Remote_Controller_USB_Keyboard_Mouse-event-kbd"
      key_code: 13 # vol up
  action:
    service: script.music_box_volume_up1
    
- alias: RF Vol-Up long press-> Vol up 10
  trigger:
    platform: event
    event_type: keyboard_remote2_command_received
    event_data:
      device_descriptor: "/dev/input/by-id/usb-OSMC_Remote_Controller_USB_Keyboard_Mouse-event-kbd"
      key_code: 1013 # vol up
  action:
    service: script.music_box_preamp_volume_up1



#webhook payload: 
#{ "action": "call_service", "service": "light.turn_on", "entity_id": "light.living_room" }      
#{ "action": "call_service", "service": "script.turn_on", "entity_id": "script.musik_station_aus" }      