- id: '1589029641106'
  alias: Amp aus wenn keine Musik auf SHD
  description: ''
  trigger:
  - entity_id: media_player.shd_studio_roon
    for: '600'
    platform: state
    to: paused
  condition:
  - condition: state
    entity_id: input_select.preamp_select
    state: LAN
  - condition: device
    device_id: f7b4ed5b4b9b4c4a8e2c1f53c67ca094
    domain: switch
    entity_id: switch.boxen_internal
    type: is_on
  action:
  - device_id: 9d479a0106de4821953e257e55f08d64
    domain: switch
    entity_id: switch.amplifier
    type: turn_off
- id: '1589029996428'
  alias: Amp an wenn Musik auf SHD
  description: ''
  trigger:
  - entity_id: media_player.shd_studio_roon
    platform: state
    to: playing
  condition:
  - condition: device
    device_id: f7b4ed5b4b9b4c4a8e2c1f53c67ca094
    domain: switch
    entity_id: switch.boxen_internal
    type: is_on
  - condition: state
    entity_id: input_select.preamp_select
    state: LAN
  action:
  - device_id: 9d479a0106de4821953e257e55f08d64
    domain: switch
    entity_id: switch.amplifier
    type: turn_on
- id: '1589030773685'
  alias: Amp aus wenn keine Musik auf Boxen Bastian
  description: ''
  trigger:
  - entity_id: media_player.boxen_bastian
    for: '600'
    platform: state
    to: paused
  condition:
  - condition: state
    entity_id: input_select.preamp_select
    state: TOSLINK
  - condition: device
    device_id: f7b4ed5b4b9b4c4a8e2c1f53c67ca094
    domain: switch
    entity_id: switch.boxen_internal
    type: is_on
  action:
  - device_id: 9d479a0106de4821953e257e55f08d64
    domain: switch
    entity_id: switch.amplifier
    type: turn_off

- id: '1589030973286'
  alias: 'Amp An wenn Musik auf Boxen Bastian '
  description: ''
  trigger:
  - entity_id: media_player.boxen_bastian
    platform: state
    to: playing
  condition:
  - condition: device
    device_id: f7b4ed5b4b9b4c4a8e2c1f53c67ca094
    domain: switch
    entity_id: switch.boxen_internal
    type: is_on
  - condition: state
    entity_id: input_select.preamp_select
    state: TOSLINK
  action:
  - device_id: 9d479a0106de4821953e257e55f08d64
    domain: switch
    entity_id: switch.amplifier
    type: turn_on
