homeassistant:
  # Name of the location where Home Assistant is runnin 
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 49.276429
  longitude: 6.970180
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 138
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:


logger:
  default: error

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: yr

# Text to speech
tts:
  - platform: google


mqtt:
    broker: 192.168.178.22
    port: 1883


# Cloud
cloud:
  google_actions:
    filter:
      exclude_entities:
        - script.tv_power
        - script.sende_tv_power
        

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml



panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.178.22:3218
    
    
switch:
  - platform: tplink
    host: 192.168.178.25
    name: Couch
  - platform: tplink
    host: 192.168.178.24
    name: Boxen
  - platform: mqtt
    name: kitchen1
    state_topic: "stat/kitchen1/POWER1"
    command_topic: "cmnd/kitchen1/POWER1"
    availability_topic: "tele/kitchen1/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"    
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: kitchen2
    state_topic: "stat/kitchen1/POWER2"
    command_topic: "cmnd/kitchen1/POWER2"
    availability_topic: "tele/kitchen1/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"    
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: basti_zimmer1
    state_topic: "stat/basti_zimmer/POWER1"
    command_topic: "cmnd/basti_zimmer/POWER1"
    availability_topic: "tele/basti_zimmer/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"    
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: basti_zimmer2
    state_topic: "stat/basti_zimmer/POWER2"
    command_topic: "cmnd/basti_zimmer/POWER2"
    availability_topic: "tele/basti_zimmer/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"    
    optimistic: false
    qos: 0
    retain: true

ifttt:
  key: !secret ifttt_key 
      
    
shell_command:
  heco2_power: irsend SEND_ONCE heco_e POWER
  tv_power: nodejs /home/pi/viera.js/tv_power.js
  tv_netflix: nodejs /home/homeassistant/.homeassistant/scripts/tv_netflix.js
  tv_power_on: /home/homeassistant/.homeassistant/scripts/tv_on.sh
  tv_power_off: /home/homeassistant/.homeassistant/scripts/tv_off.sh
  tv_tagesschau: nodejs /home/homeassistant/.homeassistant/scripts/tv_tagesschau.js
  tv_lauter: nodejs /home/homeassistant/.homeassistant/scripts/tv_lauter.js
  tv_leiser: nodejs /home/homeassistant/.homeassistant/scripts/tv_leiser.js
  tv_mute: nodejs /home/homeassistant/.homeassistant/scripts/tv_mute.js

  
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway_key
      mac: 78:11:DC:DE:D1:14
      host: 192.168.178.31

duckdns:
  domain: !secret duck_dns_domain 
  access_token: !secret duck_dns_token

