homeassistant:
  # Name of the location where Home Assistant is runnin 
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 49.276429
  longitude: 6.970180
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 138
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

recorder:
  purge_keep_days: 14
  purge_interval: 1 
  exclude:
    entities:
      - sun.sun # Don't record sun data
      - sensor.fritzbox_7490_bytes_received
      - sensor.fritzbox_7490_bytes_sent
      - sensor.fritzbox_7490_packets_received
      - sensor.fritzbox_7490_packets_sent
      - sensor.fritzbox_7490_packetssec_sent
      - sensor.fritzbox_7490_packetssec_received
#      - sensor.fritzbox_7490_kbytesec_received
#      - sensor.fritzbox_7490_kbytesec_sent

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:


logger:
  default: error
  logs: 
    custom_components.media_player.kefwireless: info
    custom_components.media_player.general_media_player: info
    roonapi: critical 
    pyfritzhome.fritzhome: critical
    pychromecast.socket_client: critical
    homeassistant.components.automation: error
    custom_components.media_player.roon: error
    homeassistant.helpers.script: error

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
   - platform: yr
   - platform: systemmonitor
     resources:
       - type: disk_use
         arg: /
       - type: memory_use_percent
       - type: processor_use
       - type: last_boot
     
   - platform: command_line
     name: CPU Temperature
     command: "cat /sys/class/thermal/thermal_zone0/temp"
     unit_of_measurement: "C"
     value_template: '{{ (value | multiply(0.001)) | round(1) }}'
    
#   - platform: filesize
#     file_paths:
#     - home-assistant_v2.db    


# Text to speech
tts:
  - platform: google


mqtt:
    broker: 192.168.178.22
    port: 1883


# Cloud
cloud:
  google_actions:
    filter:
      include_entities:
        - light.bastian_decke
        - light.bastian_lampe
        - light.couchlicht
        - light.tischlicht
        - light.wohnzimmerlicht        
        - light.kuechenlicht
        - light.thekenlicht   
        - light.kammerlicht     
        - switch.roonserver
        - switch.media_pc
        - switch.carbon_x1
        - switch.boxen
        - script.sende_tv_power_on
        - script.sende_tv_power_off        
        - script.kueche_on
        - script.kueche_off
        - script.kuechen_licht_01_minute
        - script.kuechen_licht_02_minuten
        - script.kuechen_licht_05_minuten
        - script.kuechen_licht_10_minuten
        - script.kuechen_licht_60_minuten
#        - script.zeit_fuer_fernsehen
#        - script.zeit_fuer_netflix
#        - script.zeit_fuer_tagesschau 
        - script.gute_nacht
        - script.tv_lauter
        - script.tv_leiser
        - script.tv_mute
        - script.bastian_lichtwechsel
        - script.bastian_playstation
        - script.nele_fernsehen
        - script.nele_serien_streamen    
        - script.bastian_heizung_aus
        - script.bastian_heizung_hoch
        - script.bastian_heizung_mittel
        - media_player.sprout100        
        - climate.bastian__comet_dect

#      exclude_entities:
#        - script.tv_power
#        - script.sende_tv_power
#        - light.gateway_light_7811dcded114
#      include_entities:
#        - script.sende_tv_power_on
#      include_domains:        
#        - script


#      include_entities:
#       - switch.couch    
#       - switch.kueche_decke
##       - switch.kueche_theke
#       - switch.basti_decke  
#       - switch.basti_lampe      
#       - switch.04200102dc4f222a335a # Tisch
#      - switch.roonserver
#       - switch.boxen
#       - script.kueche_on
#       - script.kueche_off       
#       - script.kuechen_licht_01_minute    
#       - script.kuechen_licht_05_minuten  


#      include_entities:
#        - script      

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml



panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: http://192.168.178.22:3218
    

light:
  - platform: switch
    name: Bastian Decke
    entity_id: switch.basti_decke
  - platform: switch
    name: Bastian Lampe
    entity_id: switch.basti_lampe
  - platform: switch
    name: Kuechenlicht
    entity_id: switch.kueche_decke
  - platform: switch
    name: Thekenlicht
    entity_id: switch.kueche_theke
  - platform: switch
    name: Couchlicht
    entity_id: switch.couch
  - platform: switch
    name: Tischlicht
    entity_id: switch.04200102dc4f222a335a
  - platform: switch
    name: Wohnzimmerlicht
    entity_id: switch.wohnzimmer_decke
  - platform: switch
    name: Kammerlicht
    entity_id: switch.kammer

   
    
switch:
  - platform: template
    switches:
      wohnzimmer_decke:
        friendly_name: "Wohnzimmer Decke"
        value_template: "off"
        turn_on:
          service: script.wohnzimmer_decke_an_aus
        turn_off:
          service: script.wohnzimmer_decke_an_aus    
      roonserver:
        friendly_name: "Media Center"
        value_template: "{{ is_state('switch.roon_server_internal', 'on') }}"
        turn_on:
          service: switch.turn_on
          data:
            entity_id: switch.roon_server_internal
        turn_off:
          service: switch.turn_off
          data:
            entity_id: switch.roon_server_internal
      boxen:
        friendly_name: "Boxen"
        value_template: "{{ is_state('switch.boxen_internal', 'on') }}"
        turn_on:               
          service: script.musik_station_an
        turn_off:
          service: script.musik_station_aus
  - platform: tplink
    host: 192.168.178.29
    name: Couch
  - platform: tplink
    host: 192.168.178.28
    name: boxen_internal
  - platform: tplink
    host: 192.168.178.58
    name: roon_server_internal
  - platform: mqtt
    name: kueche_decke
    state_topic: "stat/kitchen1/POWER1"
    command_topic: "cmnd/kitchen1/POWER1"
    availability_topic: "tele/kitchen1/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"    
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: kueche_theke
    state_topic: "stat/kitchen1/POWER2"
    command_topic: "cmnd/kitchen1/POWER2"
    availability_topic: "tele/kitchen1/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"    
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: basti_lampe
    state_topic: "stat/basti_zimmer/POWER1"
    command_topic: "cmnd/basti_zimmer/POWER1"
    availability_topic: "tele/basti_zimmer/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"    
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: basti_decke
    state_topic: "stat/basti_zimmer/POWER2"
    command_topic: "cmnd/basti_zimmer/POWER2"
    availability_topic: "tele/basti_zimmer/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"    
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: basti_lampe_internal
    friendly_name: Basti Lampe
    state_topic: "stat/basti_lampe/POWER"
    command_topic: "cmnd/basti_lampe/POWER"
    availability_topic: "tele/basti_lampe/LWT"
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "online"
    payload_not_available: "offline"    
    optimistic: false
    qos: 0
    retain: true
  - platform: mqtt
    name: "Kammer"
    state_topic: "shellies/shelly1-500936/relay/0"
    command_topic: "shellies/shelly1-500936/relay/0/command"
    payload_on: "on"
    payload_off: "off"
    retain: false
  - platform: wake_on_lan
    name: "Media PC"
    mac_address: "00:23:24:f9:d3:79"
    host: "192.168.178.53"
    turn_off:
      service: shell_command.thinkcentre_shutdown_h
  - platform: wake_on_lan
    name: "Carbon X1"
    mac_address: "54:e1:ad:d9:3f:52"
    host: "192.168.178.21"



ifttt:
  key: !secret ifttt_key 
      
    
shell_command:
  heco2_power: irsend SEND_ONCE heco_e POWER
  tv_power: nodejs /home/pi/viera.js/tv_power.js
  tv_netflix: nodejs /home/homeassistant/.homeassistant/scripts/tv_netflix.js
  tv_power_on: /home/homeassistant/.homeassistant/scripts/tv_on.sh
  tv_power_off: /home/homeassistant/.homeassistant/scripts/tv_off.sh
  tv_tagesschau: nodejs /home/homeassistant/.homeassistant/scripts/tv_tagesschau.js
  tv_lauter: nodejs /home/homeassistant/.homeassistant/scripts/tv_lauter.js
  tv_leiser: nodejs /home/homeassistant/.homeassistant/scripts/tv_leiser.js
  tv_mute: nodejs /home/homeassistant/.homeassistant/scripts/tv_mute.js
  volumio_shutdown_h: /home/homeassistant/.homeassistant/scripts/vol_shutdown_h.sh
  volumio_shutdown_r: /home/homeassistant/.homeassistant/scripts/vol_shutdown_r.sh
#  thinkcentre_shutdown_h: /home/homeassistant/.homeassistant/scripts/tc_shutdown_h.sh
  thinkcentre_shutdown_r: /home/homeassistant/.homeassistant/scripts/tc_shutdown_r.sh
  thinkcentre_shutdown_h: /home/homeassistant/.homeassistant/scripts/tc_shutdown_s.sh
  thinkcentre_wakeup_wol: /home/homeassistant/.homeassistant/scripts/tc_wakeup.sh

  
xiaomi_aqara:
  discovery_retry: 5
  gateways:
    - key: !secret xiaomi_gateway_key
      mac: 78:11:DC:DE:D1:14
      host: 192.168.178.23

duckdns:
  domain: !secret duck_dns_domain 
  access_token: !secret duck_dns_token

tuya:
  username: !secret tuya_login
  password: !secret tuya_password
  country_code: 49
  platform: smart_life
  
rest_command:
  music_box_next:
    url: 'http://192.168.178.67/api/v1/commands/?cmd=next'  
  music_box_prev:
    url: 'http://192.168.178.67/api/v1/commands/?cmd=prev'      
  music_box_toggle_play_pause:
    url: 'http://192.168.178.67/api/v1/commands/?cmd=toggle'      
  music_box_play:
    url: 'http://192.168.178.67/api/v1/commands/?cmd=play'      
  music_box_pause:
    url: 'http://192.168.178.67/api/v1/commands/?cmd=pause'      
  music_box_volumne_up:
    url: 'http://192.168.178.67/api/v1/commands/?cmd=volume&volume=plus'
  music_box_volumne_down:
    url: 'http://192.168.178.67/api/v1/commands/?cmd=volume&volume=minus' 

media_player:
  - platform: roon
    host: 192.168.178.53   
  - platform: kefwireless
    host: 192.168.178.152
    name: MyLS50W
    turn_on_service: remote.send_command
    turn_on_data: '{ "entity_id": "remote.harmony_hub","command" : "PowerToggle","device": "58830425","delay_secs": "0.1"}'
  - platform: general_media_player
    name: Sprout100
    toggle_service: remote.send_command
    toggle_data: '{ "entity_id": "remote.officehub","command" : "PowerToggle","device": "59192507","delay_secs": "0.1"}'
    mute_service: remote.send_command
    mute_data: '{ "entity_id": "remote.officehub","command" : "Mute","device": "59192507","delay_secs": "0.1"}'
    volume_up_service: remote.send_command
    volume_up_data: '{ "entity_id": "remote.officehub","command" : "VolumeUp","device": "59192507","delay_secs": "0.1"}'
    volume_down_service: remote.send_command
    volume_down_data: '{ "entity_id": "remote.officehub","command" : "VolumeDown","device": "59192507","delay_secs": "0.1"}'

   
       
#input_number:
#  roon_volume:
#    name: Player volume
#    icon: mdi:volume-high
#    min: 0
#    max: 1
#    step: 0.01
#input_select:
#  roon_playlists:
#    name: 'Playlist:'
#    options:
#      - Select playlist
#    initial: Select playlist
#    icon: mdi:spotify
#  roon_players:
#    name: 'Room:'
#    options:
#      - Select room
#    initial: Select room
#    icon: mdi:speaker-wireless     

# configuration.yaml entry
#hello_service:

fritzbox:
  devices:
    - host: fritz.box
      username: !secret fritz_login
      password: !secret fritz_password
      
#climate:
#  platform: fritzbox      


remote:
  - platform: harmony
    name: Harmony Hub
    host: 192.168.178.61
  - platform: harmony
    name: Office-Hub
    host: 192.168.178.63

    
device_tracker:
  - platform: life360
    username: !secret life360_username
    password: !secret life360_password
    prefix: life360
    show_as_state: driving, moving, places
    driving_speed: 18
    max_gps_accuracy: 200
    max_update_wait:
      minutes: 45

emulated_hue:
  host_ip: 192.168.178.22
  listen_port: 8300
  off_maps_to_on_domains:
    - script
    - scene
  expose_by_default: true
  exposed_domains:
    - light
    - switch
  entities:
    light.bastian_decke:
      name: hue_bastian_decke

